# Generated by Django 5.1.1 on 2026-02-14 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0002_labresult_delete_labresults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_opinion', models.TextField()),
                ('recommendation', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to=settings.AUTH_USER_MODEL)),
                ('lab_result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dianosis', to='labs.labresult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
