# Generated by Django 5.1.1 on 2026-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_availabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinical_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
