# Generated by Django 5.1.1 on 2026-02-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_clinical_note_appointment_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
