# Generated by Django 5.1.1 on 2026-02-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_clinical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='occurrence_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
