# Generated by Django 5.1.1 on 2026-02-14 08:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Required. A valid email address.', max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, help_text='User date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text='User address')),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin'), ('staff', 'Staff')], default='patient', help_text='Type of user in the system', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Staff Status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='Email Verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the user registered', verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last time the user logged in', null=True, verbose_name='Last Login')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the user information was updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the patient', max_length=5)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=17)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship with emergency contact', max_length=100)),
                ('license_number', models.CharField(blank=True, help_text='Professional license number', max_length=100, null=True, unique=True)),
                ('specialization', models.CharField(blank=True, help_text='Medical specialization (for doctors)', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Department or unit', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications_enabled', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(default='Administration', max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_appointments', models.BooleanField(default=True)),
                ('can_manage_billing', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=200)),
                ('sub_specialization', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('medical_school', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications')),
                ('department', models.CharField(blank=True, max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_for_consultation', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated languages', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='LabTechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications')),
                ('specialization', models.CharField(blank=True, help_text='Lab specialization (e.g., Hematology, Microbiology)', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(default='Laboratory', max_length=200)),
                ('shift_timing', models.CharField(blank=True, help_text='e.g., Morning, Evening, Night', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Technician Profile',
                'verbose_name_plural': 'Lab Technician Profiles',
                'db_table': 'lab_technician_profiles',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address for OTP verification', max_length=254, verbose_name='Email Address')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], default='registration', help_text='Purpose of the OTP', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the OTP has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the OTP was created')),
                ('expires_at', models.DateTimeField(help_text='When the OTP expires')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_verified'], name='otps_email_671b90_idx'), models.Index(fields=['otp_code'], name='otps_otp_cod_0f54dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('allergies', models.TextField(blank=True, help_text='List of known allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic medical conditions')),
                ('current_medications', models.TextField(blank=True, help_text='Current medications')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
    ]
