# Generated by Django 5.1.1 on 2026-02-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the OTP expires', null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-digit OTP code', max_length=6),
        ),
    ]
