# Generated by Django 6.0.2 on 2026-02-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_patientprofile_doctorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_nunmber',
            new_name='phone_number',
        ),
    ]
