# Generated by Django 5.2.12 on 2026-03-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_category_doctorprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
